In [3]:
import numpy as np
import pandas as pd
import dimod
from dwave.system import EmbeddingComposite, DWaveSampler
import dwave.inspector


In [4]:
###########  Generating Random QUBO  ###############

M = np.random.random((4,4))
P = M.T + M
print(P)

[[1.08269966 0.95921834 1.16614819 0.80679562]
 [0.95921834 1.33398325 1.02094704 0.95546451]
 [1.16614819 1.02094704 0.09223871 0.44627789]
 [0.80679562 0.95546451 0.44627789 0.90869096]]


In [5]:

bqm_qubo = dimod.BinaryQuadraticModel.from_numpy_matrix(P)
print(bqm_qubo)
print('\n\n',bqm_qubo.to_numpy_matrix().astype(float))

BinaryQuadraticModel({0: 1.082699660122509, 1: 1.3339832501451168, 2: 0.09223871110771009, 3: 0.9086909621187236}, {(0, 1): 1.9184366873596248, (0, 2): 2.3322963887932255, (0, 3): 1.6135912327268733, (1, 2): 2.041894089414144, (1, 3): 1.9109290264556862, (2, 3): 0.8925557725863487}, 0.0, 'BINARY')


 [[1.08269966 1.91843669 2.33229639 1.61359123]
 [0.         1.33398325 2.04189409 1.91092903]
 [0.         0.         0.09223871 0.89255577]
 [0.         0.         0.         0.90869096]]


In [6]:
sampler = EmbeddingComposite(DWaveSampler(solver={'qpu': True}))
sampleset = sampler.sample(bqm_qubo, num_reads=20)
print(sampleset)

   0  1  2  3   energy num_oc. chain_.
0  0  0  0  0      0.0      10     0.0
1  0  0  1  0 0.092239      10     0.0
['BINARY', 2 rows, 20 samples, 4 variables]


In [7]:
dwave.inspector.show(sampleset)

'http://127.0.0.1:18000/?problemId=f2c84349-0e10-4f41-af3d-9641e84c39b0'