In [1]:
# !pip install amplify
# !pip install amplify[extra]

In [2]:
from amplify import BinaryMatrix
import numpy as np

# **Binary matrix or QUBO matrix**

In [3]:
#########  Binary matrix or QUBO matrix #########

a1 = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0])  #with only upper triangular term from numpy array
m1 = BinaryMatrix(3, a1)
print(m1,'\n')


a2 = np.array([1.0, 2.0, 3.0, 0.0, 4.0, 5.0, 0.0, 0.0, 6.0])  # with all terms in 1d numpy array
m2 = BinaryMatrix(3, a2)
print(m2,'\n')


a3 = np.array([[1.0, 2.0, 3.0], [0.0, 4.0, 5.0], [0.0, 0.0, 6.0]])  # with 2d numy array
m3 = BinaryMatrix(a3)
print(m3)

print(m1==m2==m3)

[[1, 2, 3],
 [0, 4, 5],
 [0, 0, 6]] 

[[1, 2, 3],
 [0, 4, 5],
 [0, 0, 6]] 

[[1, 2, 3],
 [0, 4, 5],
 [0, 0, 6]]
True


In [4]:
#### Changing entry of binary matrix (numpy indexing)

m3[2,2] = 9

print(m3)

[[1, 2, 3],
 [0, 4, 5],
 [0, 0, 9]]


### Binary matrix methods

In [5]:
print(m3.to_Poly())  # to Binary polynomial

2.000000 q_0 q_1 + 3.000000 q_0 q_2 + 5.000000 q_1 q_2 + q_0 + 4.000000 q_1 + 9.000000 q_2


In [6]:
print(m3.to_IsingMatrix())  # to ising matrix

([[1.75, 0.5, 0.75],
 [0, 3.75, 1.25],
 [0, 0, 6.5]], 9.5)


In [7]:
print(m3.to_numpy())  # to numpy array

[[1. 2. 3.]
 [0. 4. 5.]
 [0. 0. 9.]]


In [8]:
print(m3.size())  # dimension of Binary matrix or QUBO

3


## **Evaluating value of Binary matrix**

In [9]:
print(m3.evaluate([1,1,0]))  ## with binary string

print(m3.evaluate([2,-1,5]))  # with mixed integers

7.0
234.0


# Basic algebric operations(addition, multiplication, subtraction, division) can be implemented on Binary matrix 