In [1]:
import dimod

# Defining our starting QUBO

In [2]:
linear = {0: -4.4, 1: 0.6, 2: -2}
quadratic = {(0,1): 2.8, (1,2):-0.8}
offset = 2.4

bqm_qubo = dimod.BinaryQuadraticModel(linear,quadratic,offset,dimod.Vartype.BINARY)
print(bqm_qubo)
print('\n',bqm_qubo.to_numpy_matrix().astype(float))

BinaryQuadraticModel({0: -4.4, 1: 0.6, 2: -2.0}, {(0, 1): 2.8, (1, 2): -0.8}, 2.4, 'BINARY')

 [[-4.4  2.8  0. ]
 [ 0.   0.6 -0.8]
 [ 0.   0.  -2. ]]


# Adding Variable

In [3]:
# Adding linear interaction to 2nd variable in QUBO

bqm_qubo.add_variable(1,0.4)  

print(bqm_qubo.to_numpy_matrix().astype(float))

[[-4.4  2.8  0. ]
 [ 0.   1.  -0.8]
 [ 0.   0.  -2. ]]


In [4]:
# Adding a NEW 3rd variable with linear interaction in QUBO

bqm_qubo.add_variable(3,0.5)  

print(bqm_qubo.to_numpy_matrix().astype(float))

[[-4.4  2.8  0.   0. ]
 [ 0.   1.  -0.8  0. ]
 [ 0.   0.  -2.   0. ]
 [ 0.   0.   0.   0.5]]


In [5]:
# Adding more than one variable (linear bias) using dictionary
bqm_qubo.add_variables_from({4:7.7,5:6.6}) 

print(bqm_qubo.to_numpy_matrix().astype(float))

[[-4.4  2.8  0.   0.   0.   0. ]
 [ 0.   1.  -0.8  0.   0.   0. ]
 [ 0.   0.  -2.   0.   0.   0. ]
 [ 0.   0.   0.   0.5  0.   0. ]
 [ 0.   0.   0.   0.   7.7  0. ]
 [ 0.   0.   0.   0.   0.   6.6]]


# Removing Variable

In [6]:
## Removing a single variable

bqm_qubo.remove_variable(3)

print(bqm_qubo)     # 4th variable removed

BinaryQuadraticModel({0: -4.4, 1: 1.0, 2: -2.0, 4: 7.7, 5: 6.6}, {(0, 1): 2.8, (1, 2): -0.8}, 2.4, 'BINARY')


In [7]:
# Removing multiple variables

bqm_qubo.remove_variables_from([4,5])

print(bqm_qubo)

BinaryQuadraticModel({0: -4.4, 1: 1.0, 2: -2.0}, {(0, 1): 2.8, (1, 2): -0.8}, 2.4, 'BINARY')


# Adding Interactions

In [8]:
# Adding interaction between 0-2

bqm_qubo.add_interaction(0, 2, 0.9)
print(bqm_qubo.to_numpy_matrix().astype(float))

[[-4.4  2.8  0.9]
 [ 0.   1.  -0.8]
 [ 0.   0.  -2. ]]


In [9]:
# Adding new (4th) variable and interaction

bqm_qubo.add_interaction(1, 3, 1.5)
print(bqm_qubo.to_numpy_matrix().astype(float))

[[-4.4  2.8  0.9  0. ]
 [ 0.   1.  -0.8  1.5]
 [ 0.   0.  -2.   0. ]
 [ 0.   0.   0.   0. ]]


In [10]:
# Adding multiple interactions

bqm_qubo.add_interactions_from({(0,3):1.1,(2,3):3.3})
print(bqm_qubo.to_numpy_matrix().astype(float))

[[-4.4  2.8  0.9  1.1]
 [ 0.   1.  -0.8  1.5]
 [ 0.   0.  -2.   3.3]
 [ 0.   0.   0.   0. ]]


# Removing Interactions

In [11]:
# Removing single interaction (keeps the variable)

bqm_qubo.remove_interaction(0,3)
print(bqm_qubo.to_numpy_matrix().astype(float))

[[-4.4  2.8  0.9  0. ]
 [ 0.   1.  -0.8  1.5]
 [ 0.   0.  -2.   3.3]
 [ 0.   0.   0.   0. ]]


In [12]:
# Reemoving multiple interactions (keeps variable)

bqm_qubo.remove_interactions_from([(1,3),(2,3)])
print(bqm_qubo.to_numpy_matrix().astype(float))

[[-4.4  2.8  0.9  0. ]
 [ 0.   1.  -0.8  0. ]
 [ 0.   0.  -2.   0. ]
 [ 0.   0.   0.   0. ]]


# Adding and Removing offset

In [13]:
print(bqm_qubo)  # look here the offset is 2.4

BinaryQuadraticModel({0: -4.4, 1: 1.0, 2: -2.0, 3: 0.0}, {(0, 1): 2.8, (0, 2): 0.9, (1, 2): -0.8}, 2.4, 'BINARY')


In [14]:
# Removing the offset
bqm_qubo.remove_offset()

print(bqm_qubo)   # Notice the offset is zero

BinaryQuadraticModel({0: -4.4, 1: 1.0, 2: -2.0, 3: 0.0}, {(0, 1): 2.8, (0, 2): 0.9, (1, 2): -0.8}, 0.0, 'BINARY')


In [15]:
# Adding the offset
bqm_qubo.add_offset(0.99)

print(bqm_qubo)

BinaryQuadraticModel({0: -4.4, 1: 1.0, 2: -2.0, 3: 0.0}, {(0, 1): 2.8, (0, 2): 0.9, (1, 2): -0.8}, 0.99, 'BINARY')


# Normalizing a BQM

In [16]:
# Normalizing a QUBO
bqm_qubo.normalize()

print(bqm_qubo.to_numpy_matrix().astype(float))
print(bqm_qubo) # offset changed

[[-1.          0.63636364  0.20454545  0.        ]
 [ 0.          0.22727273 -0.18181818  0.        ]
 [ 0.          0.         -0.45454545  0.        ]
 [ 0.          0.          0.          0.        ]]
BinaryQuadraticModel({0: -1.0, 1: 0.22727272727272727, 2: -0.45454545454545453, 3: 0.0}, {(0, 1): 0.6363636363636364, (0, 2): 0.20454545454545453, (1, 2): -0.18181818181818182}, 0.22499999999999998, 'BINARY')


# Multiplying BQM with scalar

In [17]:
bqm_qubo.scale(10)

print(bqm_qubo.to_numpy_matrix().astype(float))
print(bqm_qubo) 

[[-10.           6.36363636   2.04545455   0.        ]
 [  0.           2.27272727  -1.81818182   0.        ]
 [  0.           0.          -4.54545455   0.        ]
 [  0.           0.           0.           0.        ]]
BinaryQuadraticModel({0: -10.0, 1: 2.2727272727272725, 2: -4.545454545454545, 3: 0.0}, {(0, 1): 6.363636363636363, (0, 2): 2.0454545454545454, (1, 2): -1.8181818181818183}, 2.25, 'BINARY')


# See bqm.update